# Generated by Django 4.0.6 on 2022-07-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counseling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=64)),
                ('number', models.IntegerField(max_length=64)),
            ],
        ),
    ]
