# Generated by Django 4.0.6 on 2022-07-30 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_counseling_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counseling',
            name='user',
        ),
    ]
